"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_grad0)\
$os\
$username\
[](fg:color_grad0 bg:color_grad1)\
$directory\
[](fg:color_grad1 bg:color_grad2)\
$git_branch\
$git_status\
[](fg:color_grad2 bg:color_grad3)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
[](fg:color_grad3 bg:color_bg1)\
$cmd_duration\
[](fg:color_bg1 bg:color_bg0)\
${custom.clocktime}\
[ ](fg:color_bg0)\
$line_break$character"""

palette = 'custom'

#ash colors 1 (gotten through okLCH python script)
#00b3d0
#0092e0

#ash colors 2
#0092e0
#486fe5

#void colors 1 (gotten through gimp)
#4094c2
#6757c2

#ash colors 3
#00a9d3
#3d76e7

#ash colors 4
#1685e9
#5e5adc

[palettes.custom]
color_fg0 = '#fbf1c7'
color_bg0 = '#3c3836'
color_bg1 = '#665c54'
#grad stands for gradient
color_grad0 = '#19d1c3'
color_grad1 = '#1685e9'
color_grad2 = '#5e5adc'
color_grad3 = '#8e1ac2'
#as far as i can tell these are all for cursor color
color_purple = '#b16286'
color_green = '#00d930'
color_yellow = '#d79921'
color_red = '#cc241d'

[os]
disabled = false
style = "bg:color_grad0 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_grad0 fg:color_fg0"
style_root = "bg:color_grad0 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_grad1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_grad2"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_grad2)]($style)'

[git_status]
style = "bg:color_grad2"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_grad2)]($style)'

[nodejs]
symbol = ""
style = "bg:color_grad3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grad3)]($style)'

[c]
symbol = " "
style = "bg:color_grad3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grad3)]($style)'

[rust]
symbol = ""
style = "bg:color_grad3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grad3)]($style)'

[golang]
symbol = ""
style = "bg:color_grad3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grad3)]($style)'

[php]
symbol = ""
style = "bg:color_grad3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grad3)]($style)'

[java]
symbol = ""
style = "bg:color_grad3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grad3)]($style)'

[kotlin]
symbol = ""
style = "bg:color_grad3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grad3)]($style)'

[haskell]
symbol = ""
style = "bg:color_grad3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grad3)]($style)'

[python]
symbol = ""
style = "bg:color_grad3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grad3)]($style)'

[lua]
symbol = ""
style = "bg:color_grad3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grad3)]($style)'

[cmd_duration]
show_milliseconds = true
style = "bg:color_bg1"
format= '[[  $duration](fg:color_fg0 bg:color_bg1)]($style)'

[time]
disabled = false
time_format = "%H:%M %P"
style = "bg:color_bg0"
format = '[[  $time ](fg:color_fg0 bg:color_bg0)]($style)'
time_range = '00:00:00-11:32:00'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[  ](bold fg:color_green)'
error_symbol = '[  ](bold fg:color_red)'
vimcmd_symbol = '[  ](bold fg:color_green)'
vimcmd_replace_one_symbol = '[  ](bold fg:color_purple)'
vimcmd_replace_symbol = '[  ](bold fg:color_purple)'
vimcmd_visual_symbol = '[  ](bold fg:color_yellow)'

#[custom.linhome]
#symbol = " "
#when = '''test "$HOME" = "$PWD"'''
#format = '[$symbol]($style)'

[custom.clocktime]
command = '~/.config/starshipscripts/clocktime.sh'
when = true
style = "bg:color_bg0"
format = '[[($output)](fg:color_fg0 bg:color_bg0)]($style)'
